version: '3'

services:
    rsshub:
        image: tosea/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
        depends_on:
            - redis
            - browserless

    browserless:
        # See issue 6680
        # ports:
            # - '3000:3000' 
        image: browserless/chrome:latest
        restart: always
        environment: 
            - DEFAULT_LAUNCH_ARGS=["--window-size=1920,1080", "--ignore-certifcate-errors-spki-list", "--ignore-certifcate-errors", "--disable-setuid-sandbox"]
            # - PROXY_URL=socks5://127.0.0.1:8888
            # -  "--proxy-server=http://127.0.0.1:8888"
        ulimits:
          core:
            hard: 0
            soft: 0

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

volumes:
    redis-data:
